tap "drud/ddev"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "yt-dlp/taps"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Console Matrix
brew "cmatrix"
# Test various flash cards
brew "f3"
# OpenType text shaping engine
brew "harfbuzz"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# GNU utilities for networking
brew "inetutils"
# Sophisticated file transfer program
brew "lftp"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# Collection of tools that nobody wrote when UNIX was young
brew "moreutils"
# Tiny, lightning fast, feature-packed file manager
brew "nnn"
# Libraries for security-enabled client and server applications
brew "nss"
# Manage multiple Node.js versions
brew "nvm"
# File browser
brew "ranger"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Internet file retriever
brew "wget"
# Local development environment management system
brew "drud/ddev/ddev"
# A youtube-dl fork with additional features and fixes
brew "yt-dlp/taps/yt-dlp"
# Web browser focusing on privacy
cask "brave-browser"
# Free and open-source web browser
cask "chromium"
# Photography workflow application and raw developer
cask "darktable"
# Web browser
cask "firefox"
# Web browser
cask "google-chrome"
# Web browser
cask "google-chrome-canary"
# Graphically shows disk usage within a file system
cask "grandperspective"
# File archiver
cask "keka"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Web browser
cask "microsoft-edge"
# Set of tools to create, alter and inspect Matroska files (MKV)
cask "mkvtoolnix"
# Media player based on MPlayer and mplayer2
cask "mpv"
cask "sensiblesidebuttons"
# MySQL/MariaDB database management platform
cask "sequel-pro"
# Move and resize windows with ease
cask "spectacle"
# Desktop client for Telegram messenger
cask "telegram-desktop"
# To-do list
cask "todoist"
# Virtualizer for x86 hardware
cask "virtualbox"
# Open-source code editor
cask "visual-studio-code"
# Desktop client for WhatsApp
cask "whatsapp"
